config/routes.rb
Rails.application.routes.draw do

  root 'projections#index'

  resources :projections, :members, :statements, :terms

  get 'd3_get_chart_source_data', to: 'projections#d3_get_chart_source_data'

end

app/models/statement.rb
class Statement < ActiveRecord::Base
  belongs_to :member

  scope :exclude_non_voting, ->(nonvoting) do
    unless nonvoting.nil? || nonvoting.blank?
      joins('JOIN terms on terms.member_id = statements.member_id').where('(statements.statement_date BETWEEN terms.start_date AND terms.end_date) OR (statements.statement_date >= terms.start_date AND terms.end_date IS NULL)')
    else
      all
    end
  end

  scope :exclude_similar_to_prior, ->(similar) do
    unless similar.nil? || similar.blank?
      where("similar_to_prior = ?", false)
    else
      all
    end
  end

  scope :exclude_non_voting_as_of_now, ->(nonvoting) do
    unless nonvoting.nil? || nonvoting.blank?
      joins('JOIN terms on terms.member_id = statements.member_id').where('(now()::date BETWEEN terms.start_date AND terms.end_date) OR (now()::date >= terms.start_date AND terms.end_date IS NULL)')
    else
      all
    end
  end

end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController

  http_basic_authenticate_with :name => ENV['FED_USERNAME'], :password => ENV['FED_PASSWORD'], except: [:index, :show]

  before_action :set_statement, only: [:show, :edit, :update, :destroy]

  def index
    @statements = Statement.exclude_non_voting(params[:filter]).exclude_non_voting_as_of_now(params[:filter_as_of_now]).exclude_similar_to_prior(params[:filter_when_prior]).order(statement_date: :desc)
    respond_to do |format|
      format.html
      format.json { render json: @statements }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @statement }
    end
  end

  def new

    respond_to do |format|
      format.html {
        @statements = Statement.all.order(statement_date: :desc)
        @statement = Statement.new
      }
      format.js {
        @statements = Statement.where(:member_id => params[:member_id].to_i).order(statement_date: :desc)
      }
    end

  end

  def edit
  end

  def create
    @statement = Statement.new(statement_params)

      if @statement.save
        redirect_to @statement, notice: 'New statement was successfully created.'
      else
        render action: 'new'
      end
  end


  def update
    if @statement.update(statement_params)
      redirect_to @statement
    else
      render action: 'edit'
    end
  end

  def destroy
    @statement.destroy
    redirect_to projections_path
  end

  private

  def set_statement
    @statement = Statement.find(params[:id])
  end

  def statement_params
    params.require(:statement).permit(:url, :summary, :lean, :pub_date, :statement_date, :similar_to_prior, :member_id)
  end

end

app/views/statements/_form.html.erb
<%= form_for @statement do |f| %>

  <div class="field form-group">
    <%= f.collection_select(:member_id, Member.all, :id, :name) %>
  </div>

  <div class="field form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: "form-control", rows: 10 %>
  </div>

  <div class="field form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :lean %>
    <%= f.text_field :lean, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label "Substantially similar to prior statement(s)" %>
    <%= f.check_box :similar_to_prior %>
  </div>

  <div class="field form-group">
    <%= f.label :statement_date %>
    <%= f.date_select :statement_date %>
  </div>

  <div class="field form-group">
    <%= f.label :pub_date %>
    <%= f.date_select :pub_date %>
  </div>

  <div class="field form-group">
    <%= f.submit("Submit", class: "btn btn-primary") %>
  </div>

<% end %>

app/views/statements/_statementstable.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Summary</th>
      <th>Lean</th>
      <th>Statement Date</th>
      <th>Publication Date</th>
    </tr>
  </thead>
  <tbody>
    <% counter = 0 %>
    <% statements.each do |statement| %>
    <% counter += 1 %>
    <tr>
      <td><span class="badge"><%= link_to counter.to_s, statement_path(statement), style: "all: inherit" %></span>
      &nbsp;<%= link_to statement.member.name, member_path(statement.member) %> <%= statement.summary %>
      <%= link_to '<span class="glyphicon glyphicon-paperclip"></span>'.html_safe, statement.url, :target => "_blank" %>
      <% if statement.similar_to_prior %>
      &nbsp;<span class="label label-default">Similar to Prior Statement</span>
      <% end %>
      </td>
      <td><%= statement.lean %></td>
      <td><%= statement.statement_date.strftime("%B %-d, %Y") unless statement.statement_date.nil? %></td>
      <td><%= statement.pub_date.strftime("%B %-d, %Y") unless statement.pub_date.nil? %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/statements/edit.html.erb
<div class="col-xs-12">

<h1>Edit Statement</h1>

<%= render 'form' %>
<%= link_to 'Back', projections_path %>

</div>

app/views/statements/index.html.erb
<div class="col-md-2 hidden-xs"></div>
<div class="col-xs-12 col-md-8">

<h1>Statements</h1>
<p>&nbsp;</p>
<%= form_tag({controller: 'statements', action: 'index'}, method: 'get', id: 'filter_form') do %>
  <div class="form-group">
  <%= label_tag(:filter, "Exclude non-voting members at time of statement") %>
  <%= check_box_tag(:filter, "true", params.has_key?(:filter) ? true : false) %>
  <br>
  <%= label_tag(:filter_as_of_now, "Exclude currently non-voting members") %>
  <%= check_box_tag(:filter_as_of_now, "true", params.has_key?(:filter_as_of_now) ? true : false) %>
  <br>
  <%= label_tag(:filter_when_prior, "Exclude statements substantially similar to prior ones by the same member") %>
  <%= check_box_tag(:filter_when_prior, "true", params.has_key?(:filter_when_prior) ? true : false) %>
  </div>
<% end %>

<script>
  document.getElementById('filter').addEventListener('change', function() {
    document.getElementById('filter_form').submit();
  }, false);
  document.getElementById('filter_as_of_now').addEventListener('change', function() {
    document.getElementById('filter_form').submit();
  }, false);
  document.getElementById('filter_when_prior').addEventListener('change', function() {
    document.getElementById('filter_form').submit();
  }, false);
</script>
<%= render :partial => 'statementstable', :locals => { :statements => @statements } %>
<%= link_to "All Members", members_path, class: "btn btn-default" %>
<p/>
</div>
<div class="col-md-2 hidden-xs"></div>

app/views/statements/new.html.erb
<div class="col-xs-12 col-sm-4">

<h1>New Statement</h1>

<%= render 'form' %>
<%= link_to 'Back', projections_path %>

</div>
<div class="hidden-xs col-sm-8" id="statementslist" style="position:fixed;overflow-y:scroll;overflow-x: hidden; top: 70px; bottom: 0;right: 0;">
  <%= render :partial => 'statementstable', :locals => { :statements => @statements } %>
</div>

<script>
  $("#statement_member_id").change(function() {
    $.ajax({
      type: "GET",
      url: "<%= new_statement_path %>" + "?member_id=" + document.getElementById("statement_member_id").value,
      dataType: "script"
    });
	});
</script>

app/views/statements/new.js.erb
$("#statementslist").empty().append("<%= escape_javascript (render partial: 'statementstable', locals: {statements: @statements}) %>");

app/views/statements/show.html.erb
<div class="col-xs-12">

<h1>Statement</h1>

<p>
  <strong>Name:</strong> <%= @statement.member.name %>
</p>

<p>
  <strong>Summary:</strong> <%= @statement.summary %> <%= link_to '<span class="glyphicon glyphicon-paperclip"></span>'.html_safe, @statement.url, :target => "_blank" %>
</p>

<p>
  <strong>Lean:</strong> <%= @statement.lean %>
</p>

<p>
  <strong>Substantially Similar to Prior Statements:</strong> <%= @statement.similar_to_prior ? "Yes" : "No" %>
</p>

<p>
  <strong>Statement Date:</strong> <%= @statement.statement_date.strftime("%B %-d, %Y") %>
</p>

<p>
  <strong>Publication Date:</strong> <%= @statement.pub_date.strftime("%B %-d, %Y") %>
</p>

<%= link_to "All Members", members_path, class: "btn btn-default" %>
<%= link_to "All Statements", statements_path, class: "btn btn-default" %>

</div>